name: Maven Package

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b
##      - uses: s4u/setup-maven-action@< version >
        with:
          java-version: '11'
          maven-version: '3.3.9'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
